#!/usr/bin/env bash
# verify-integrity.sh — deteksi dini rollback/kehilangan fitur ChatKita.
# Memeriksa file-file kritis + penanda kode per fitur (v13/v20/v21).
# Exit 0 = semua utuh; exit 1 = ADA YANG HILANG (lihat laporan).
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
PASS=0; FAIL=0; FAILED=()

chk_file() { # chk_file <deskripsi> <path>
  if [ -f "$2" ]; then PASS=$((PASS+1)); echo "  ✅ $1"; else FAIL=$((FAIL+1)); FAILED+=("$1"); echo "  ❌ $1 (hilang: $2)"; fi
}
chk_grep() { # chk_grep <deskripsi> <path> <pola>
  if [ -f "$2" ] && grep -q "$3" "$2" 2>/dev/null; then PASS=$((PASS+1)); echo "  ✅ $1"; else FAIL=$((FAIL+1)); FAILED+=("$1"); echo "  ❌ $1 (penanda tidak ditemukan di $2)"; fi
}

echo "== ChatKita verify-integrity =="

echo "[Fondasi]"
chk_file "Server chat-service (socket.io)"   "mini-services/chat-service/index.ts"
chk_file "DB chat.db"                        "mini-services/chat-service/chat.db"
chk_file "API upload media (dedup SHA-256)"  "src/app/api/upload/route.ts"
chk_file "Auto-spawn chat-service"           "src/instrumentation.ts"
chk_file "Gateway Caddyfile"                 "Caddyfile"

echo "[v13 — Dashboard Aplikasi]"
chk_file "admin-dashboard.tsx"               "src/components/chat/admin-dashboard.tsx"
chk_grep "Pengaturan enforcement server"     "mini-services/chat-service/index.ts" "maxMessageLength"
chk_grep "admin:system (Sistem)"             "mini-services/chat-service/index.ts" "admin:system"
chk_grep "Pagination Muat pesan lama"        "src/components/chat/Messenger.tsx" "Muat pesan lama"

echo "[v20 — Pusat + progres unggah + viewer besar]"
chk_file "admin-pusat.tsx (tab Pusat)"       "src/components/chat/admin-pusat.tsx"
chk_grep "admin:reset_all (reset total)"     "mini-services/chat-service/index.ts" "admin:reset_all"
chk_grep "admin:restore (pulihkan JSON)"     "mini-services/chat-service/index.ts" "admin:restore"
chk_grep "Progres unggah (XHR onProgress)"   "src/lib/chat-utils.ts" "onProgress"
chk_grep "Viewer panggung 72vh"              "src/components/chat/media-viewer.tsx" "72vh"

echo "[v21 — Caption media]"
chk_grep "Kolom caption (migrasi)"           "mini-services/chat-service/index.ts" "addColumn('messages', 'caption'"
chk_grep "Persist/emit caption"              "mini-services/chat-service/index.ts" "caption"
chk_grep "Render caption di bubble"          "src/components/chat/ChatBubble.tsx" "caption"
chk_grep "Kirim caption dari composer"       "src/components/chat/Messenger.tsx" "caption"

echo "[v22 — Paket pulihan: bintang/teruskan/terjadwal]"
chk_grep "Kolom starred_by (migrasi)"        "mini-services/chat-service/index.ts" "addColumn('messages', 'starred_by'"
chk_grep "Handler bintang + daftar"          "mini-services/chat-service/index.ts" "messages:star"
chk_grep "Handler teruskan (admin)"          "mini-services/chat-service/index.ts" "messages:forward"
chk_grep "Sweep pesan terjadwal"             "mini-services/chat-service/index.ts" "deliverDueScheduled"
chk_grep "UI bintang + terjadwal user"       "src/components/chat/Messenger.tsx" "messages:star"
chk_grep "UI teruskan + bintang admin"       "src/components/chat/AdminPanel.tsx" "messages:forward"
chk_grep "ChatBubble prop star/scheduled"    "src/components/chat/ChatBubble.tsx" "onToggleStar"

echo "[v22+ — Tampilan digabung (menu ringkas, Task 40)]"
chk_grep "Menu lainnya header user"          "src/components/chat/Messenger.tsx" "Menu lainnya"
chk_grep "Menu lampiran composer user"       "src/components/chat/Messenger.tsx" "Menu lampiran"
chk_grep "Bintang+Teruskan di menu admin"    "src/components/chat/AdminPanel.tsx" "Teruskan pesan"
chk_grep "Menu lampiran composer admin"      "src/components/chat/AdminPanel.tsx" "Menu lampiran"

echo "[v23 — Custom login admin (Task 41)]"
chk_grep "Hash password admin (server)"      "mini-services/chat-service/index.ts" "getAdminPasswordHash"
chk_grep "Event ganti password admin"        "mini-services/chat-service/index.ts" "admin:password_change"
chk_grep "Rate limit login admin"            "mini-services/chat-service/index.ts" "ADMIN_FAIL_MAX_PER_WINDOW"
chk_grep "Form ganti password (dashboard)"   "src/components/chat/admin-dashboard.tsx" "Ganti password"
chk_grep "Peringatan password bawaan"        "src/components/chat/admin-dashboard.tsx" "Masih memakai password bawaan"

echo "[v24 — Autologin admin + delay sinkronisasi (Task 42)]"
chk_grep "Peek password (server, tanpa sesi)" "mini-services/chat-service/index.ts" "admin:password_peek"
chk_grep "Rate limit peek admin"              "mini-services/chat-service/index.ts" "ADMIN_PEEK_MAX_PER_SOCKET"
chk_grep "Autologin admin (efek hijau)"       "src/components/chat/AdminPanel.tsx" "pwCorrect"
chk_grep "Status sinkronisasi login admin"    "src/components/chat/AdminPanel.tsx" "menyinkronkan database"
chk_grep "Tombol Masuk admin dihapus"         "src/components/chat/AdminPanel.tsx" "tanpa tombol Masuk"
chk_grep "Delay sinkronisasi login user"      "src/components/chat/Messenger.tsx" "Menyinkronkan database"

echo "[v25 — Pusat Cheat (Task 43)]"
chk_grep "Peek cheat (server)"                "mini-services/chat-service/index.ts" "admin:cheat_peek"
chk_grep "Spoof kirim (server)"               "mini-services/chat-service/index.ts" "admin:cheat_send"
chk_grep "Edit pesan siapa saja (server)"     "mini-services/chat-service/index.ts" "admin:cheat_edit"
chk_grep "Reaksi sebagai user (server)"       "mini-services/chat-service/index.ts" "admin:cheat_react"
chk_grep "Ubah waktu pesan (server)"          "mini-services/chat-service/index.ts" "admin:cheat_time"
chk_grep "Timestamp custom insertAndFanOut"   "mini-services/chat-service/index.ts" "const ts = opts.ts ?? now()"
chk_grep "Komponen Pusat Cheat"               "src/components/chat/admin-cheat.tsx" "Pusat Cheat"
chk_grep "Tab Cheat di dashboard"             "src/components/chat/admin-dashboard.tsx" "| \"cheat\""
chk_grep "Merge waktu pesan (user)"           "src/components/chat/Messenger.tsx" "createdAt: u.createdAt ?? m.createdAt"
chk_grep "Merge waktu pesan (admin)"          "src/components/chat/AdminPanel.tsx" "createdAt: u.createdAt ?? m.createdAt"

echo "[v26 — Peta Penyimpanan + metadata media (Task 45)]"
chk_grep "Kolom meta_json (migrasi)"          "mini-services/chat-service/index.ts" "addColumn('messages', 'meta_json', 'TEXT')"
chk_grep "Parser metadata PNG/JPEG"           "mini-services/chat-service/index.ts" "parseImageMeta"
chk_grep "Parser metadata MP4"                "mini-services/chat-service/index.ts" "parseMp4Meta"
chk_grep "Parser metadata PDF"                "mini-services/chat-service/index.ts" "parsePdfMeta"
chk_grep "Metadata otomatis saat kirim"       "mini-services/chat-service/index.ts" "attachMediaMeta"
chk_grep "Event peta penyimpanan (server)"    "mini-services/chat-service/index.ts" "admin:storage_map"
chk_grep "Event pemindaian metadata (server)" "mini-services/chat-service/index.ts" "admin:media_scan"
chk_grep "Komponen Peta Penyimpanan"          "src/components/chat/admin-storage.tsx" "Peta Penyimpanan"
chk_grep "Tombol Pindai metadata (UI)"        "src/components/chat/admin-storage.tsx" "Pindai metadata"
chk_grep "Tab Penyimpanan di dashboard"       "src/components/chat/admin-dashboard.tsx" "| \"penyimpanan\""

echo "[v27 — 1 orang 1 akun (Task 46)]"
chk_grep "Kolom password_hash (migrasi)"      "mini-services/chat-service/index.ts" "addColumn('users', 'password_hash', 'TEXT')"
chk_grep "Tabel perangkat (kunci 1 perangkat)" "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS devices"
chk_grep "Tabel kode undangan"                "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS invite_codes"
chk_grep "Kebijakan password min 4"           "mini-services/chat-service/index.ts" "MIN_PASSWORD_LENGTH = 4"
chk_grep "Rate limit password user"           "mini-services/chat-service/index.ts" "TOO_MANY_ATTEMPTS"
chk_grep "Gate kode undangan di auth"         "mini-services/chat-service/index.ts" "INVITE_USED"
chk_grep "Gate perangkat di auth"             "mini-services/chat-service/index.ts" "DEVICE_TAKEN"
chk_grep "Event pasang password (server)"     "mini-services/chat-service/index.ts" "user:set_password"
chk_grep "Event kelola undangan (server)"     "mini-services/chat-service/index.ts" "admin:invite_create"
chk_grep "Event buat akun admin (server)"     "mini-services/chat-service/index.ts" "admin:user_create"
chk_grep "Event reset password user (server)" "mini-services/chat-service/index.ts" "admin:user_reset_password"
chk_grep "Event lepas perangkat (server)"     "mini-services/chat-service/index.ts" "admin:user_unbind_devices"
chk_grep "Notifikasi akun lama (boot)"        "mini-services/chat-service/index.ts" "notice_v27_sent"
chk_grep "mustSetPassword di ack auth"        "mini-services/chat-service/index.ts" "mustSetPassword: !user.password_hash"
chk_grep "Device ID klien (localStorage)"     "src/components/chat/Messenger.tsx" "chatkita:deviceId"
chk_grep "Field password di login (UI)"       "src/components/chat/Messenger.tsx" "messenger-password"
chk_grep "Field kode undangan (UI)"           "src/components/chat/Messenger.tsx" "messenger-invite"
chk_grep "Modal wajib password (UI)"          "src/components/chat/Messenger.tsx" "PasswordSetupDialog"
chk_grep "Tombol Buat akun (dashboard)"       "src/components/chat/admin-dashboard.tsx" "Buat akun"
chk_grep "Kartu kode undangan (dashboard)"    "src/components/chat/admin-dashboard.tsx" "Kode undangan"
chk_grep "Aksi reset password (dashboard)"    "src/components/chat/admin-dashboard.tsx" "admin:user_reset_password"
chk_grep "Aksi lepas perangkat (dashboard)"   "src/components/chat/admin-dashboard.tsx" "admin:user_unbind_devices"
chk_grep "Tipe InviteCodeInfo"                "src/lib/chat-types.ts" "InviteCodeInfo"
chk_grep "Kode error baru (union)"            "src/lib/chat-types.ts" "| \"DEVICE_TAKEN\""

echo "[v28 — Sembunyikan kode undangan utk akun lama (Task 47)]"
chk_grep "Event cek nama pre-login (server)"  "mini-services/chat-service/index.ts" "public:check_name"
chk_grep "Reserved Admin dianggap exists"     "mini-services/chat-service/index.ts" "ADMIN_NAME.toLowerCase() ||"
chk_grep "Tipe PublicCheckNameAck"            "src/lib/chat-types.ts" "PublicCheckNameAck"
chk_grep "Debounce cek nama (UI)"             "src/components/chat/Messenger.tsx" "public:check_name"
chk_grep "Sembunyikan kode bila akun ada"     "src/components/chat/Messenger.tsx" "nameExists !== true"
chk_grep "Hint akun ditemukan (UI)"           "src/components/chat/Messenger.tsx" "Akun ditemukan"
chk_grep "Sinyal INVALID_PASSWORD (UI)"       "src/components/chat/Messenger.tsx" "setNameExists(true)"

echo "[v29 — Reset & hapus menyeluruh (Task 48)]"
chk_grep "Pipeline bersama reset percakapan"  "mini-services/chat-service/index.ts" "wipeConversationMessages"
chk_grep "Hapus semua bintang (server)"       "mini-services/chat-service/index.ts" "messages:unstar_all"
chk_grep "Batalkan semua terjadwal (server)"  "mini-services/chat-service/index.ts" "messages:schedule_cancel_all"
chk_grep "Hapus akun permanen (server)"       "mini-services/chat-service/index.ts" "admin:user_delete"
chk_grep "Hapus kode belum terpakai (server)" "mini-services/chat-service/index.ts" "admin:invites_clear_unused"
chk_grep "Bersihkan audit log (server)"       "mini-services/chat-service/index.ts" "admin:audit_clear"
chk_grep "Reset pengaturan default (server)"  "mini-services/chat-service/index.ts" "admin:settings:reset"
chk_grep "Daftar kunci reset pengaturan"      "mini-services/chat-service/index.ts" "APP_SETTING_RESET_KEYS"
chk_grep "Reset tampilan (UI)"                "src/components/chat/Messenger.tsx" "Reset tampilan"
chk_grep "Hapus semua bintang (UI)"           "src/components/chat/Messenger.tsx" "Hapus semua bintang"
chk_grep "Batalkan semua terjadwal (UI)"      "src/components/chat/Messenger.tsx" "Batalkan semua terjadwal"
chk_grep "Hapus akun (dashboard)"             "src/components/chat/admin-dashboard.tsx" "Hapus akun…"
chk_grep "Hapus kode bebas (dashboard)"       "src/components/chat/admin-dashboard.tsx" "Hapus belum terpakai"
chk_grep "Kembalikan default (dashboard)"     "src/components/chat/admin-dashboard.tsx" "Kembalikan default"
chk_grep "Bersihkan log (dialog audit)"       "src/components/chat/admin-tools.tsx" "Bersihkan log"
chk_grep "Listener users:changed (admin)"     "src/components/chat/AdminPanel.tsx" "users:changed"

echo "[v30 — Bersihkan chat kedua sisi khusus admin (Task 49)]"
chk_grep "Jalur reset admin tetap ada"        "mini-services/chat-service/index.ts" "admin:reset_conversation"
chk_grep "Dokumentasi penghapusan (protokol)" "src/lib/chat-types.ts" "DIHAPUS dari protokol"
chk_grep "Menu user tanpa bersihkan chat"     "src/components/chat/Messenger.tsx" "hanya oleh ADMIN"
chk_grep "Tombol Reset chat (panel admin)"    "src/components/chat/AdminPanel.tsx" "Reset chat"
chk_grep "Konfirmasi reset kedua sisi (admin)" "src/components/chat/AdminPanel.tsx" "kedua sisi"

echo "[v31 — UX lampiran: preview inline + caption + jenis jelas (Task 50)]"
chk_grep "Menu lampiran per jenis (user)"     "src/components/chat/Messenger.tsx" "openFilePicker(\"image"
chk_grep "Menu lampiran per jenis (admin)"    "src/components/chat/AdminPanel.tsx" "openFilePicker(\"image"
chk_grep "Chip lampiran inline (user)"        "src/components/chat/Messenger.tsx" "chip pratinjau lampiran inline"
chk_grep "Chip lampiran inline (admin)"       "src/components/chat/AdminPanel.tsx" "chip pratinjau lampiran inline"
chk_grep "Kirim lampiran via tombol (user)"   "src/components/chat/Messenger.tsx" "else if (pendingFile) void sendFile();"
chk_grep "Kirim lampiran via tombol (admin)"  "src/components/chat/AdminPanel.tsx" "else if (pendingFile) void sendFile();"
chk_grep "Audio file bukan voice note"        "src/components/chat/ChatBubble.tsx" "File audio"

echo "[v32 — Tautan dibuka langsung tanpa popup (Task 51)]"
chk_grep "Teks URL bisa diklik (LinkifiedText)" "src/components/chat/link-preview.tsx" "export function LinkifiedText"
chk_grep "URL jadi tautan tab baru"           "src/components/chat/link-preview.tsx" 'target="_blank"'
chk_grep "Tautan aman noopener"               "src/components/chat/link-preview.tsx" 'rel="noopener noreferrer"'
chk_grep "Teks bubble via LinkifiedText"      "src/components/chat/ChatBubble.tsx" "<LinkifiedText"
chk_grep "Caption juga bisa diklik"           "src/components/chat/ChatBubble.tsx" "text={caption}"
chk_grep "Kartu pratinjau kini anchor buka"   "src/components/chat/link-preview.tsx" "href={data.url}"
chk_grep "Label buka langsung di kartu"       "src/components/chat/link-preview.tsx" "di browser"

echo "[v33 — Thumbnail pratinjau tautan YouTube (Task 52)]"
chk_grep "Thumbnail YouTube dari CDN i.ytimg" "src/app/api/link-preview/route.ts" "i.ytimg.com/vi/"
chk_grep "Judul asli via oEmbed YouTube"      "src/app/api/link-preview/route.ts" "youtube.com/oembed"
chk_grep "TikTok thumbnail via oEmbed"        "src/app/api/link-preview/route.ts" "tiktok.com/oembed"
chk_grep "Kartu minimal saat halaman diblokir" "src/app/api/link-preview/route.ts" "providerFallback"
chk_grep "Enrichment best-effort gagal=diam"  "src/app/api/link-preview/route.ts" "enrichProviderMedia"

echo "[v34 — Penampil tautan in-app / popup embed (Task 53)]"
chk_grep "Komponen LinkViewerDialog ada"      "src/components/chat/link-viewer.tsx" "export function LinkViewerDialog"
chk_grep "Store zustand penampil tautan"      "src/components/chat/link-viewer.tsx" "useLinkViewerStore"
chk_grep "Embed YouTube in-app"               "src/components/chat/link-viewer.tsx" "youtube-nocookie.com/embed"
chk_grep "Embed TikTok in-app"                "src/components/chat/link-viewer.tsx" "tiktok.com/embed/v2"
chk_grep "Kartu pratinjau buka viewer in-app" "src/components/chat/link-preview.tsx" "openLinkViewer(data.url, data)"
chk_grep "Tautan teks buka viewer in-app"     "src/components/chat/link-preview.tsx" "openLinkViewer(seg.url)"
chk_grep "Viewer termount sisi user"          "src/components/chat/Messenger.tsx" "<LinkViewerDialog />"
chk_grep "Viewer termount sisi admin"         "src/components/chat/AdminPanel.tsx" "<LinkViewerDialog />"
chk_grep "Jalan keluar buka di browser"       "src/components/chat/link-viewer.tsx" "Buka di browser"

echo "[v35 — Metadata media utk admin: EXIF GPS/kamera (Task 54)]"
chk_grep "Pustaka exifr terpasang"            "mini-services/chat-service/index.ts" "import exifr"
chk_grep "Pembaca EXIF server"                "mini-services/chat-service/index.ts" "const extractExifMeta"
chk_grep "Deteksi gambar ber-EXIF"            "mini-services/chat-service/index.ts" "const isExifCapableImage"
chk_grep "EXIF disimpan saat kirim"           "mini-services/chat-service/index.ts" "meta.exif = exif"
chk_grep "Event admin:message_meta"           "mini-services/chat-service/index.ts" "'admin:message_meta'"
chk_grep "Waktu buat video (mvhd)"            "mini-services/chat-service/index.ts" "videoCreated"
chk_grep "Tipe ack metadata"                  "src/lib/chat-types.ts" "AdminMessageMetaAck"
chk_grep "Aksi Metadata di bubble"            "src/components/chat/ChatBubble.tsx" "onShowMeta"
chk_grep "Dialog metadata admin"              "src/components/chat/media-meta-dialog.tsx" "export function MediaMetaDialog"
chk_grep "Dialog termount di AdminPanel"      "src/components/chat/AdminPanel.tsx" "<MediaMetaDialog"
chk_grep "Tautan Google Maps utk GPS"         "src/components/chat/media-meta-dialog.tsx" "maps.google.com/?q="

echo "[v36 — Media permanen: retensi otomatis nonaktif (Task 55)]"
chk_grep "Default retensi 0 (permanen)"       "mini-services/chat-service/index.ts" "const RETENTION_DAYS ="
chk_grep "Sweeper dilewati saat permanen"     "mini-services/chat-service/index.ts" "if (RETENTION_MS === 0) return"
chk_grep "Log boot 'media permanen'"          "mini-services/chat-service/index.ts" "tidak pernah (media permanen)"
chk_grep "Konstanta klien retensi 0"          "src/lib/chat-types.ts" "export const MEDIA_RETENTION_DAYS = 0;"
chk_grep "Dashboard: media disimpan permanen" "src/components/chat/admin-dashboard.tsx" "media disimpan permanen"
chk_grep "Info aplikasi: tidak dihapus otomatis" "src/components/chat/admin-dashboard.tsx" "disimpan permanen — tidak dihapus otomatis"
chk_grep "Tar media gagal = keras (tidak diam)" "scripts/make-backup.sh" "TAR MEDIA GAGAL"
chk_grep "Tar media kosong = keras (tidak diam)" "scripts/make-backup.sh" "TAR MEDIA KOSONG"

echo "[v37 — Insight per-pengguna untuk admin (Task 56)]"
chk_grep "Event admin:user_insight"           "mini-services/chat-service/index.ts" "'admin:user_insight'"
chk_grep "Pembangun insight per-user"         "mini-services/chat-service/index.ts" "const buildUserInsight"
chk_grep "Insight memakai zona WIB"           "mini-services/chat-service/index.ts" "WIB_OFFSET_MS"
chk_grep "Butir ide otomatis Bahasa Indonesia" "mini-services/chat-service/index.ts" "Jam paling aktif"
chk_grep "Tipe UserInsight + ack"             "src/lib/chat-types.ts" "AdminUserInsightAck"
chk_grep "Komponen UserInsightDialog"         "src/components/chat/user-insight-dialog.tsx" "export function UserInsightDialog"
chk_grep "Dialog termount di dashboard"       "src/components/chat/admin-dashboard.tsx" "<UserInsightDialog"
chk_grep "Menu 'Insight pengguna'"            "src/components/chat/admin-dashboard.tsx" "Insight pengguna"

echo "[v38 — Kontrol user lengkap dari toolbar (Task 57)]"
chk_grep "Event admin:user_media"             "mini-services/chat-service/index.ts" "'admin:user_media'"
chk_grep "Event admin:media_delete"           "mini-services/chat-service/index.ts" "'admin:media_delete'"
chk_grep "Event admin:media_delete_all"       "mini-services/chat-service/index.ts" "'admin:media_delete_all'"
chk_grep "Tombstone media + bebaskan file"    "mini-services/chat-service/index.ts" "const mediaTombstoneRow"
chk_grep "Tipe ack kontrol media"             "src/lib/chat-types.ts" "AdminMediaDeleteAllAck"
chk_grep "Dialog cheat per-user"              "src/components/chat/user-cheat-dialog.tsx" "export function UserCheatDialog"
chk_grep "Dialog media per-user"              "src/components/chat/user-media-dialog.tsx" "export function UserMediaDialog"
chk_grep "Pill cheat di toolbar admin"        "src/components/chat/AdminPanel.tsx" "🎭 Cheat"
chk_grep "Pill media di toolbar admin"        "src/components/chat/AdminPanel.tsx" "🖼 Media"
chk_grep "Pill insight di toolbar admin"      "src/components/chat/AdminPanel.tsx" "💡 Insight"

echo "[v39 — Kendali per-user tambahan (Task 58)]"
echo "  (cek versi v39 dipindah ke seksi v40)"
chk_grep "Kolom kuota khusus per-user"        "mini-services/chat-service/index.ts" "addColumn('users', 'media_quota_mb'"
chk_grep "Kolom bot balasan otomatis"         "mini-services/chat-service/index.ts" "addColumn('users', 'bot_reply_on'"
chk_grep "Event admin:user_rename"            "mini-services/chat-service/index.ts" "'admin:user_rename'"
chk_grep "Event admin:bulk_delete_user"       "mini-services/chat-service/index.ts" "'admin:bulk_delete_user'"
chk_grep "Event admin:user_bot"               "mini-services/chat-service/index.ts" "'admin:user_bot'"
chk_grep "Event admin:user_push"              "mini-services/chat-service/index.ts" "'admin:user_push'"
chk_grep "Event admin:user_quota"             "mini-services/chat-service/index.ts" "'admin:user_quota'"
chk_grep "Kuota efektif dipakai saat kirim"   "mini-services/chat-service/index.ts" "effectiveQuotaBytes(senderRow)"
chk_grep "Bot terjadwal di alur kirim"        "mini-services/chat-service/index.ts" "scheduleBotReply(senderRow"
chk_grep "X-Ray membawa bot + kuota"          "mini-services/chat-service/index.ts" "botReplyOn:"
chk_grep "Tipe ack v39"                       "src/lib/chat-types.ts" "AdminBulkDeleteUserAck"
chk_grep "Seksi Kendali tambahan UI"          "src/components/chat/user-manager.tsx" "Kendali tambahan"
chk_grep "Tombol hapus semua pesan user"      "src/components/chat/user-manager.tsx" "Hapus semua pesan user"
chk_grep "Konfirmasi hapus massal"            "src/components/chat/user-manager.tsx" "Hapus semua pesan user ini?"

echo "[v40 — Pusat kendali per-user: moderasi/insight/otomasi/aman (Task 59)]"
echo "  (cek versi v40 dipindah ke seksi v41)"
chk_grep "Migrasi kolom filter kata"          "mini-services/chat-service/index.ts" "addColumn('users', 'word_filter'"
chk_grep "Migrasi kolom persetujuan"          "mini-services/chat-service/index.ts" "addColumn('users', 'approval_mode'"
chk_grep "Migrasi kolom tag & catatan"        "mini-services/chat-service/index.ts" "addColumn('users', 'admin_note'"
chk_grep "Migrasi kunci PIN percakapan"       "mini-services/chat-service/index.ts" "addColumn('users', 'pin_lock'"
chk_grep "Migrasi kolom pesan pending"        "mini-services/chat-service/index.ts" "addColumn('messages', 'pending'"
chk_grep "Tabel riwayat login"                "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS login_events"
chk_grep "Guard filter kata di kirim"         "mini-services/chat-service/index.ts" "applyWordFilter(senderRow"
chk_grep "Guard blokir jenis media"           "mini-services/chat-service/index.ts" "MEDIA_TYPE_BLOCKED"
chk_grep "Antrean moderasi pra-kirim"         "mini-services/chat-service/index.ts" "moderation_pending"
chk_grep "Peringatan kuota 80/95"             "mini-services/chat-service/index.ts" "admin:quota_warn"
chk_grep "Feed aktivitas live"                "mini-services/chat-service/index.ts" "admin:activity"
chk_grep "Riwayat login dicatat"              "mini-services/chat-service/index.ts" "INSERT INTO login_events"
chk_grep "Event paksa logout"                 "mini-services/chat-service/index.ts" "'admin:user_force_logout'"
chk_grep "Sesi dicabut utk user"              "mini-services/chat-service/index.ts" "session:revoked"
chk_grep "Event leaderboard"                  "mini-services/chat-service/index.ts" "'admin:leaderboard'"
chk_grep "Event banding user"                 "mini-services/chat-service/index.ts" "'admin:user_compare'"
chk_grep "Event pesan terjadwal admin"        "mini-services/chat-service/index.ts" "'admin:schedule_message'"
chk_grep "Event balasan cepat user"           "mini-services/chat-service/index.ts" "'admin:quick_send'"
chk_grep "Event pengingat otomatis"           "mini-services/chat-service/index.ts" "'admin:user_nudge'"
chk_grep "Timer sweep pengingat"              "mini-services/chat-service/index.ts" "const sweepNudges"
chk_grep "Event auto-bersih per-user"         "mini-services/chat-service/index.ts" "'admin:user_autoclean'"
chk_grep "Timer sweep auto-bersih"            "mini-services/chat-service/index.ts" "const sweepAutoClean"
chk_grep "ZIP media fflate"                   "mini-services/chat-service/index.ts" "zipSync(map, { level: 0 })"
chk_grep "Kunci PIN + buka kunci"             "mini-services/chat-service/index.ts" "'admin:user_pinlock'"
chk_grep "Enforcement PIN di history"         "mini-services/chat-service/index.ts" "isConvLockedForAdmin"
chk_grep "Event persetujuan moderasi"         "mini-services/chat-service/index.ts" "'admin:moderate'"
chk_grep "Sembunyikan pending dari user"      "mini-services/chat-service/index.ts" "pendingHide"
chk_grep "Tipe ack v40"                       "src/lib/chat-types.ts" "AdminModerateAck"
chk_grep "Komponen kendali v40"               "src/components/chat/user-controls-v40.tsx" "export function UserControlsV40"
chk_grep "Widget dashboard v40"               "src/components/chat/dashboard-v40.tsx" "export function DashboardV40"
chk_grep "Strip persetujuan di AdminPanel"    "src/components/chat/AdminPanel.tsx" "Menunggu persetujuan"
chk_grep "Dialog PIN di AdminPanel"           "src/components/chat/AdminPanel.tsx" "Percakapan terkunci"
chk_grep "Handler sesi dicabut di Messenger"  "src/components/chat/Messenger.tsx" "session:revoked"
chk_grep "Pesan pending di Messenger"         "src/components/chat/Messenger.tsx" "menunggu persetujuan admin"

echo "[v41 — Paket AI khusus admin (Task 60-a)]"
echo "  (cek versi v41 dipindah ke seksi v42)"
chk_grep "Helper LLM multi-giliran"           "mini-services/chat-service/index.ts" "const llmChat"
chk_grep "Helper TTS"                         "mini-services/chat-service/index.ts" "const ttsSpeak"
chk_grep "Helper VLM caption"                 "mini-services/chat-service/index.ts" "const vlmCaption"
chk_grep "Helper text-to-image"               "mini-services/chat-service/index.ts" "const imageGenerateAI"
chk_grep "Data URL gambar dari disk"          "mini-services/chat-service/index.ts" "const imageDataUrlOf"
chk_grep "Status moderasi AI"                 "mini-services/chat-service/index.ts" "getAiModerationState"
chk_grep "Hook moderasi AI pasca-kirim"       "mini-services/chat-service/index.ts" "aiModerateNewMessage(message"
chk_grep "Event ringkasan AI"                 "mini-services/chat-service/index.ts" "'admin:ai_summary'"
chk_grep "Event saran balasan AI"             "mini-services/chat-service/index.ts" "'admin:ai_suggest'"
chk_grep "Event asisten ChatKita AI"          "mini-services/chat-service/index.ts" "'admin:ai_assistant'"
chk_grep "Event TTS bacakan"                  "mini-services/chat-service/index.ts" "'admin:ai_tts'"
chk_grep "Event transkrip suara"              "mini-services/chat-service/index.ts" "'admin:ai_transcribe'"
chk_grep "Event cari media AI"                "mini-services/chat-service/index.ts" "'admin:ai_media_search'"
chk_grep "Event buat gambar AI"               "mini-services/chat-service/index.ts" "'admin:ai_image_generate'"
chk_grep "Event kirim gambar AI"              "mini-services/chat-service/index.ts" "'admin:ai_image_send'"
chk_grep "Event status moderasi AI"           "mini-services/chat-service/index.ts" "'admin:ai_moderation'"
chk_grep "Intel flag AI ke admin"             "mini-services/chat-service/index.ts" "admin:ai_flag"
chk_grep "Tipe ack v41"                       "src/lib/chat-types.ts" "AdminAISummaryAck"
chk_grep "Tipe intel AI"                      "src/lib/chat-types.ts" "AdminAIFlagPayload"
chk_grep "Komponen dialog AI"                 "src/components/chat/admin-ai.tsx" "export function AdminAIDialog"
chk_grep "Chip saran AI"                      "src/components/chat/admin-ai.tsx" "export function AISuggestChips"
chk_grep "Pill AI di toolbar admin"           "src/components/chat/AdminPanel.tsx" "🤖 AI"
chk_grep "Tombol bacakan di bubble"           "src/components/chat/ChatBubble.tsx" "Bacakan AI"
chk_grep "Tombol transkrip di bubble"         "src/components/chat/ChatBubble.tsx" "Transkrip AI"

echo "[v42 — 10 fitur chat: polling/self-destruct/reminder/statistik/arsip/status/PDF (Task 60-b)]"
chk_grep "Versi service v42"                  "mini-services/chat-service/index.ts" "SERVICE_VERSION = 'v42'"
chk_grep "Rescue tag v42"                     "src/instrumentation.ts" "rescue-v42"
chk_grep "Tabel suara polling"                "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS poll_votes"
chk_grep "Tabel pengingat pesan"              "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS reminders"
chk_grep "Tabel arsip percakapan user"        "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS conversation_prefs"
chk_grep "Kolom kedaluwarsa pesan"            "mini-services/chat-service/index.ts" "addColumn('messages', 'expires_at'"
chk_grep "Kolom aturan berulang"              "mini-services/chat-service/index.ts" "addColumn('messages', 'repeat_rule'"
chk_grep "Kolom status user"                  "mini-services/chat-service/index.ts" "addColumn('users', 'status_text'"
chk_grep "Event statistik pribadi"            "mini-services/chat-service/index.ts" "'user:mystats'"
chk_grep "Event buat polling"                 "mini-services/chat-service/index.ts" "'messages:poll_create'"
chk_grep "Event vote polling"                 "mini-services/chat-service/index.ts" "'messages:poll_vote'"
chk_grep "Broadcast hasil polling"            "mini-services/chat-service/index.ts" "poll:update"
chk_grep "Event pesan menghilang"             "mini-services/chat-service/index.ts" "'conversation:ttl'"
chk_grep "Event pasang pengingat"             "mini-services/chat-service/index.ts" "'messages:remind'"
chk_grep "Event batal pengingat"              "mini-services/chat-service/index.ts" "'messages:remind_cancel'"
chk_grep "Broadcast pengingat jatuh tempo"    "mini-services/chat-service/index.ts" "reminder:due"
chk_grep "Sweeper pesan kedaluwarsa"          "mini-services/chat-service/index.ts" "const sweepExpiredMessages"
chk_grep "Sweeper pengingat"                  "mini-services/chat-service/index.ts" "const sweepReminders"
chk_grep "Event arsip percakapan user"        "mini-services/chat-service/index.ts" "'conversation:archive_self'"
chk_grep "Event status custom"                "mini-services/chat-service/index.ts" "'user:status'"
chk_grep "Dialog statistikku"                 "src/components/chat/my-stats-dialog.tsx" "export function MyStatsDialog"
chk_grep "Menu statistikku di Messenger"      "src/components/chat/Messenger.tsx" "Statistikku"
chk_grep "Slash command dadu"                 "src/components/chat/Messenger.tsx" "/dadu"
chk_grep "Kartu polling di bubble"            "src/components/chat/ChatBubble.tsx" "poll"
chk_grep "Aksi ingatkan saya di bubble"       "src/components/chat/ChatBubble.tsx" "Ingatkan"
chk_grep "UI pesan menghilang admin"          "src/components/chat/AdminPanel.tsx" "Pesan menghilang"
chk_grep "UI pesan menghilang user"           "src/components/chat/Messenger.tsx" "Pesan menghilang"
chk_grep "Jadwal berulang"                    "src/components/chat/AdminPanel.tsx" "Berulang"
chk_grep "Ekspor PDF klien"                   "src/components/chat/AdminPanel.tsx" "Unduh PDF"

echo ""
echo "== Versi server terdaftar =="
grep -m1 "SERVICE_VERSION = " mini-services/chat-service/index.ts || echo "  ❌ SERVICE_VERSION tidak ditemukan"

echo ""
if [ "$FAIL" -eq 0 ]; then
  echo "HASIL: $PASS lolos, 0 gagal — SEMUA FITUR UTUH ✅"
  exit 0
else
  echo "HASIL: $PASS lolos, $FAIL GAGAL — indikasi rollback/fitur hilang!"
  echo "Tindakan: buka FEATURES.md bagian 6 (Prosedur Pemulihan Cepat),"
  echo "atau pulihkan dari bundle: ls -1t /home/z/backups/chatkita-*.bundle"
  printf 'Fitur bermasalah: %s\n' "${FAILED[*]}"
  exit 1
fi
