#!/usr/bin/env bash
# verify-integrity.sh — deteksi dini rollback/kehilangan fitur ChatKita.
# Memeriksa file-file kritis + penanda kode per fitur (v13/v20/v21).
# Exit 0 = semua utuh; exit 1 = ADA YANG HILANG (lihat laporan).
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
PASS=0; FAIL=0; FAILED=()

chk_file() { # chk_file <deskripsi> <path>
  if [ -f "$2" ]; then PASS=$((PASS+1)); echo "  ✅ $1"; else FAIL=$((FAIL+1)); FAILED+=("$1"); echo "  ❌ $1 (hilang: $2)"; fi
}
chk_grep() { # chk_grep <deskripsi> <path> <pola>
  if [ -f "$2" ] && grep -q "$3" "$2" 2>/dev/null; then PASS=$((PASS+1)); echo "  ✅ $1"; else FAIL=$((FAIL+1)); FAILED+=("$1"); echo "  ❌ $1 (penanda tidak ditemukan di $2)"; fi
}

echo "== ChatKita verify-integrity =="

echo "[Fondasi]"
chk_file "Server chat-service (socket.io)"   "mini-services/chat-service/index.ts"
chk_file "DB chat.db"                        "mini-services/chat-service/chat.db"
chk_file "API upload media (dedup SHA-256)"  "src/app/api/upload/route.ts"
chk_file "Auto-spawn chat-service"           "src/instrumentation.ts"
chk_file "Gateway Caddyfile"                 "Caddyfile"

echo "[v13 — Dashboard Aplikasi]"
chk_file "admin-dashboard.tsx"               "src/components/chat/admin-dashboard.tsx"
chk_grep "Pengaturan enforcement server"     "mini-services/chat-service/index.ts" "maxMessageLength"
chk_grep "admin:system (Sistem)"             "mini-services/chat-service/index.ts" "admin:system"
chk_grep "Pagination Muat pesan lama"        "src/components/chat/Messenger.tsx" "Muat pesan lama"

echo "[v20 — Pusat + progres unggah + viewer besar]"
chk_file "admin-pusat.tsx (tab Pusat)"       "src/components/chat/admin-pusat.tsx"
chk_grep "admin:reset_all (reset total)"     "mini-services/chat-service/index.ts" "admin:reset_all"
chk_grep "admin:restore (pulihkan JSON)"     "mini-services/chat-service/index.ts" "admin:restore"
chk_grep "Progres unggah (XHR onProgress)"   "src/lib/chat-utils.ts" "onProgress"
chk_grep "Viewer panggung memenuhi panel (v58)" "src/components/chat/media-viewer.tsx" "min-h-0 w-full flex-1"

echo "[v21 — Caption media]"
chk_grep "Kolom caption (migrasi)"           "mini-services/chat-service/index.ts" "addColumn('messages', 'caption'"
chk_grep "Persist/emit caption"              "mini-services/chat-service/index.ts" "caption"
chk_grep "Render caption di bubble"          "src/components/chat/ChatBubble.tsx" "caption"
chk_grep "Kirim caption dari composer"       "src/components/chat/Messenger.tsx" "caption"

echo "[v22 — Paket pulihan: bintang/teruskan/terjadwal]"
chk_grep "Kolom starred_by (migrasi)"        "mini-services/chat-service/index.ts" "addColumn('messages', 'starred_by'"
chk_grep "Handler bintang + daftar"          "mini-services/chat-service/index.ts" "messages:star"
chk_grep "Handler teruskan (admin)"          "mini-services/chat-service/index.ts" "messages:forward"
chk_grep "Sweep pesan terjadwal"             "mini-services/chat-service/index.ts" "deliverDueScheduled"
chk_grep "UI bintang + terjadwal user"       "src/components/chat/Messenger.tsx" "messages:star"
chk_grep "UI teruskan + bintang admin"       "src/components/chat/AdminPanel.tsx" "messages:forward"
chk_grep "ChatBubble prop star/scheduled"    "src/components/chat/ChatBubble.tsx" "onToggleStar"

echo "[v22+ — Tampilan digabung (menu ringkas, Task 40)]"
chk_grep "Menu lainnya header user"          "src/components/chat/Messenger.tsx" "Menu lainnya"
chk_grep "Menu lampiran composer user"       "src/components/chat/Messenger.tsx" "Menu lampiran"
chk_grep "Bintang+Teruskan di menu admin"    "src/components/chat/AdminPanel.tsx" "Teruskan pesan"
chk_grep "Menu lampiran composer admin"      "src/components/chat/AdminPanel.tsx" "Menu lampiran"

echo "[v23 — Custom login admin (Task 41)]"
chk_grep "Hash password admin (server)"      "mini-services/chat-service/index.ts" "getAdminPasswordHash"
chk_grep "Event ganti password admin"        "mini-services/chat-service/index.ts" "admin:password_change"
chk_grep "Rate limit login admin"            "mini-services/chat-service/index.ts" "ADMIN_FAIL_MAX_PER_WINDOW"
chk_grep "Form ganti password (dashboard)"   "src/components/chat/admin-dashboard.tsx" "Ganti password"
chk_grep "Peringatan password bawaan"        "src/components/chat/admin-dashboard.tsx" "Masih memakai password bawaan"

echo "[v24 — Autologin admin + delay sinkronisasi (Task 42)]"
chk_grep "Peek password (server, tanpa sesi)" "mini-services/chat-service/index.ts" "admin:password_peek"
chk_grep "Rate limit peek admin"              "mini-services/chat-service/index.ts" "ADMIN_PEEK_MAX_PER_SOCKET"
chk_grep "Autologin admin (efek hijau)"       "src/components/chat/AdminPanel.tsx" "pwCorrect"
chk_grep "Status sinkronisasi login admin"    "src/components/chat/AdminPanel.tsx" "menyinkronkan database"
chk_grep "Tombol Masuk admin dihapus"         "src/components/chat/AdminPanel.tsx" "tanpa tombol Masuk"
chk_grep "Delay sinkronisasi login user"      "src/components/chat/Messenger.tsx" "Menyinkronkan database"

echo "[v25 — Pusat Cheat (Task 43)]"
chk_grep "Peek cheat (server)"                "mini-services/chat-service/index.ts" "admin:cheat_peek"
chk_grep "Spoof kirim (server)"               "mini-services/chat-service/index.ts" "admin:cheat_send"
chk_grep "Edit pesan siapa saja (server)"     "mini-services/chat-service/index.ts" "admin:cheat_edit"
chk_grep "Reaksi sebagai user (server)"       "mini-services/chat-service/index.ts" "admin:cheat_react"
chk_grep "Ubah waktu pesan (server)"          "mini-services/chat-service/index.ts" "admin:cheat_time"
chk_grep "Timestamp custom insertAndFanOut"   "mini-services/chat-service/index.ts" "const ts = opts.ts ?? now()"
chk_grep "Komponen Pusat Cheat"               "src/components/chat/admin-cheat.tsx" "Pusat Cheat"
chk_grep "Tab Cheat di dashboard"             "src/components/chat/admin-dashboard.tsx" "| \"cheat\""
chk_grep "Merge waktu pesan (user)"           "src/components/chat/Messenger.tsx" "createdAt: u.createdAt ?? m.createdAt"
chk_grep "Merge waktu pesan (admin)"          "src/components/chat/AdminPanel.tsx" "createdAt: u.createdAt ?? m.createdAt"

echo "[v26 — Peta Penyimpanan + metadata media (Task 45)]"
chk_grep "Kolom meta_json (migrasi)"          "mini-services/chat-service/index.ts" "addColumn('messages', 'meta_json', 'TEXT')"
chk_grep "Parser metadata PNG/JPEG"           "mini-services/chat-service/index.ts" "parseImageMeta"
chk_grep "Parser metadata MP4"                "mini-services/chat-service/index.ts" "parseMp4Meta"
chk_grep "Parser metadata PDF"                "mini-services/chat-service/index.ts" "parsePdfMeta"
chk_grep "Metadata otomatis saat kirim"       "mini-services/chat-service/index.ts" "attachMediaMeta"
chk_grep "Event peta penyimpanan (server)"    "mini-services/chat-service/index.ts" "admin:storage_map"
chk_grep "Event pemindaian metadata (server)" "mini-services/chat-service/index.ts" "admin:media_scan"
chk_grep "Komponen Peta Penyimpanan"          "src/components/chat/admin-storage.tsx" "Peta Penyimpanan"
chk_grep "Tombol Pindai metadata (UI)"        "src/components/chat/admin-storage.tsx" "Pindai metadata"
chk_grep "Tab Penyimpanan di dashboard"       "src/components/chat/admin-dashboard.tsx" "| \"penyimpanan\""

echo "[v27 — 1 orang 1 akun (Task 46)]"
chk_grep "Kolom password_hash (migrasi)"      "mini-services/chat-service/index.ts" "addColumn('users', 'password_hash', 'TEXT')"
chk_grep "Tabel perangkat (kunci 1 perangkat)" "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS devices"
chk_grep "Tabel kode undangan"                "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS invite_codes"
chk_grep "Kebijakan password min 4"           "mini-services/chat-service/index.ts" "MIN_PASSWORD_LENGTH = 4"
chk_grep "Rate limit password user"           "mini-services/chat-service/index.ts" "TOO_MANY_ATTEMPTS"
chk_grep "Gate kode undangan di auth"         "mini-services/chat-service/index.ts" "INVITE_USED"
chk_grep "Gate perangkat di auth"             "mini-services/chat-service/index.ts" "DEVICE_TAKEN"
chk_grep "Event pasang password (server)"     "mini-services/chat-service/index.ts" "user:set_password"
chk_grep "Event kelola undangan (server)"     "mini-services/chat-service/index.ts" "admin:invite_create"
chk_grep "Event buat akun admin (server)"     "mini-services/chat-service/index.ts" "admin:user_create"
chk_grep "Event reset password user (server)" "mini-services/chat-service/index.ts" "admin:user_reset_password"
chk_grep "Event lepas perangkat (server)"     "mini-services/chat-service/index.ts" "admin:user_unbind_devices"
chk_grep "Notifikasi akun lama (boot)"        "mini-services/chat-service/index.ts" "notice_v27_sent"
chk_grep "mustSetPassword di ack auth"        "mini-services/chat-service/index.ts" "mustSetPassword: !user.password_hash"
chk_grep "Device ID klien (localStorage)"     "src/components/chat/Messenger.tsx" "chatkita:deviceId"
chk_grep "Field password di login (UI)"       "src/components/chat/Messenger.tsx" "messenger-password"
chk_grep "Field kode undangan (UI)"           "src/components/chat/Messenger.tsx" "messenger-invite"
chk_grep "Modal wajib password (UI)"          "src/components/chat/Messenger.tsx" "PasswordSetupDialog"
chk_grep "Tombol Buat akun (dashboard)"       "src/components/chat/admin-dashboard.tsx" "Buat akun"
chk_grep "Kartu kode undangan (dashboard)"    "src/components/chat/admin-dashboard.tsx" "Kode undangan"
chk_grep "Aksi set password (v46: Account 360)" "src/components/chat/account-control-dialog.tsx" "admin:account_password"
chk_grep "Aksi lepas perangkat (v47: pindah ke Account 360 tab Akun)" "src/components/chat/account-control-dialog.tsx" "admin:user_unbind_devices"
chk_grep "Tipe InviteCodeInfo"                "src/lib/chat-types.ts" "InviteCodeInfo"
chk_grep "Kode error baru (union)"            "src/lib/chat-types.ts" "| \"DEVICE_TAKEN\""

echo "[v28 — Sembunyikan kode undangan utk akun lama (Task 47)]"
chk_grep "Event cek nama pre-login (server)"  "mini-services/chat-service/index.ts" "public:check_name"
chk_grep "Reserved Admin dianggap exists"     "mini-services/chat-service/index.ts" "ADMIN_NAME.toLowerCase() ||"
chk_grep "Tipe PublicCheckNameAck"            "src/lib/chat-types.ts" "PublicCheckNameAck"
chk_grep "Debounce cek nama (UI)"             "src/components/chat/Messenger.tsx" "public:check_name"
chk_grep "Sembunyikan kode bila akun ada"     "src/components/chat/Messenger.tsx" "nameExists !== true"
chk_grep "Hint akun ditemukan (UI)"           "src/components/chat/Messenger.tsx" "Akun ditemukan"
chk_grep "Sinyal INVALID_PASSWORD (UI)"       "src/components/chat/Messenger.tsx" "setNameExists(true)"

echo "[v29 — Reset & hapus menyeluruh (Task 48)]"
chk_grep "Pipeline bersama reset percakapan"  "mini-services/chat-service/index.ts" "wipeConversationMessages"
chk_grep "Hapus semua bintang (server)"       "mini-services/chat-service/index.ts" "messages:unstar_all"
chk_grep "Batalkan semua terjadwal (server)"  "mini-services/chat-service/index.ts" "messages:schedule_cancel_all"
chk_grep "Hapus akun permanen (server)"       "mini-services/chat-service/index.ts" "admin:user_delete"
chk_grep "Hapus kode belum terpakai (server)" "mini-services/chat-service/index.ts" "admin:invites_clear_unused"
chk_grep "Bersihkan audit log (server)"       "mini-services/chat-service/index.ts" "admin:audit_clear"
chk_grep "Reset pengaturan default (server)"  "mini-services/chat-service/index.ts" "admin:settings:reset"
chk_grep "Daftar kunci reset pengaturan"      "mini-services/chat-service/index.ts" "APP_SETTING_RESET_KEYS"
chk_grep "Reset tampilan (UI)"                "src/components/chat/Messenger.tsx" "Reset tampilan"
chk_grep "Hapus semua bintang (UI)"           "src/components/chat/Messenger.tsx" "Hapus semua bintang"
chk_grep "Batalkan semua terjadwal (UI)"      "src/components/chat/Messenger.tsx" "Batalkan semua terjadwal"
chk_grep "Hapus akun (v46: zona bahaya 360)"  "src/components/chat/account-control-dialog.tsx" "Hapus akun permanen"
chk_grep "Hapus kode bebas (dashboard)"       "src/components/chat/admin-dashboard.tsx" "Hapus belum terpakai"
chk_grep "Kembalikan default (dashboard)"     "src/components/chat/admin-dashboard.tsx" "Kembalikan default"
chk_grep "Bersihkan log (dialog audit)"       "src/components/chat/admin-tools.tsx" "Bersihkan log"
chk_grep "Listener users:changed (admin)"     "src/components/chat/AdminPanel.tsx" "users:changed"

echo "[v30 — Bersihkan chat kedua sisi khusus admin (Task 49)]"
chk_grep "Jalur reset admin tetap ada"        "mini-services/chat-service/index.ts" "admin:reset_conversation"
chk_grep "Dokumentasi penghapusan (protokol)" "src/lib/chat-types.ts" "DIHAPUS dari protokol"
chk_grep "Menu user tanpa bersihkan chat"     "src/components/chat/Messenger.tsx" "hanya oleh ADMIN"
chk_grep "Tombol Reset chat (panel admin)"    "src/components/chat/AdminPanel.tsx" "Reset chat"
chk_grep "Konfirmasi reset kedua sisi (admin)" "src/components/chat/AdminPanel.tsx" "kedua sisi"

echo "[v31 — UX lampiran: preview inline + caption + jenis jelas (Task 50)]"
chk_grep "Menu lampiran per jenis (user)"     "src/components/chat/Messenger.tsx" "openFilePicker(\"image"
chk_grep "Menu lampiran per jenis (admin)"    "src/components/chat/AdminPanel.tsx" "openFilePicker(\"image"
chk_grep "Chip lampiran inline (user)"        "src/components/chat/Messenger.tsx" "chip pratinjau lampiran inline"
chk_grep "Chip lampiran inline (admin)"       "src/components/chat/AdminPanel.tsx" "chip pratinjau lampiran inline"
chk_grep "Kirim lampiran via tombol (user)"   "src/components/chat/Messenger.tsx" "else if (pendingFile) void sendFile();"
chk_grep "Kirim lampiran via tombol (admin)"  "src/components/chat/AdminPanel.tsx" "else if (pendingFile) void sendFile();"
chk_grep "Audio file bukan voice note"        "src/components/chat/ChatBubble.tsx" "File audio"

echo "[v32 — Tautan dibuka langsung tanpa popup (Task 51)]"
chk_grep "Teks URL bisa diklik (LinkifiedText)" "src/components/chat/link-preview.tsx" "export function LinkifiedText"
chk_grep "URL jadi tautan tab baru"           "src/components/chat/link-preview.tsx" 'target="_blank"'
chk_grep "Tautan aman noopener"               "src/components/chat/link-preview.tsx" 'rel="noopener noreferrer"'
chk_grep "Teks bubble via LinkifiedText"      "src/components/chat/ChatBubble.tsx" "<LinkifiedText"
chk_grep "Caption juga bisa diklik"           "src/components/chat/ChatBubble.tsx" "text={caption}"
chk_grep "Kartu pratinjau kini anchor buka"   "src/components/chat/link-preview.tsx" "href={cardData.url}"
chk_grep "Label buka langsung di kartu"       "src/components/chat/link-preview.tsx" "di browser"

echo "[v33 — Thumbnail pratinjau tautan YouTube (Task 52)]"
chk_grep "Thumbnail YouTube dari CDN i.ytimg" "src/app/api/link-preview/route.ts" "i.ytimg.com/vi/"
chk_grep "Judul asli via oEmbed YouTube"      "src/app/api/link-preview/route.ts" "youtube.com/oembed"
chk_grep "TikTok thumbnail via oEmbed"        "src/app/api/link-preview/route.ts" "tiktok.com/oembed"
chk_grep "Kartu minimal saat halaman diblokir" "src/app/api/link-preview/route.ts" "providerFallback"
chk_grep "Enrichment best-effort gagal=diam"  "src/app/api/link-preview/route.ts" "enrichProviderMedia"

echo "[v34 — Penampil tautan in-app / popup embed (Task 53)]"
chk_grep "Komponen LinkViewerDialog ada"      "src/components/chat/link-viewer.tsx" "export function LinkViewerDialog"
chk_grep "Store zustand penampil tautan"      "src/components/chat/link-viewer.tsx" "useLinkViewerStore"
chk_grep "Embed YouTube in-app"               "src/components/chat/link-viewer.tsx" "youtube-nocookie.com/embed"
chk_grep "Embed TikTok in-app"                "src/components/chat/link-viewer.tsx" "tiktok.com/embed/v2"
chk_grep "Kartu pratinjau buka viewer in-app" "src/components/chat/link-preview.tsx" "openLinkViewer(cardData.url, cardData)"
chk_grep "Tautan teks buka viewer in-app"     "src/components/chat/link-preview.tsx" "openLinkViewer(seg.url)"
chk_grep "Viewer termount sisi user"          "src/components/chat/Messenger.tsx" "<LinkViewerDialog />"
chk_grep "Viewer termount sisi admin"         "src/components/chat/AdminPanel.tsx" "<LinkViewerDialog />"
chk_grep "Jalan keluar buka di browser"       "src/components/chat/link-viewer.tsx" "Buka di browser"

echo "[v35 — Metadata media utk admin: EXIF GPS/kamera (Task 54)]"
chk_grep "Pustaka exifr terpasang"            "mini-services/chat-service/index.ts" "import exifr"
chk_grep "Pembaca EXIF server"                "mini-services/chat-service/index.ts" "const extractExifMeta"
chk_grep "Deteksi gambar ber-EXIF"            "mini-services/chat-service/index.ts" "const isExifCapableImage"
chk_grep "EXIF disimpan saat kirim"           "mini-services/chat-service/index.ts" "meta.exif = exif"
chk_grep "Event admin:message_meta"           "mini-services/chat-service/index.ts" "'admin:message_meta'"
chk_grep "Waktu buat video (mvhd)"            "mini-services/chat-service/index.ts" "videoCreated"
chk_grep "Tipe ack metadata"                  "src/lib/chat-types.ts" "AdminMessageMetaAck"
chk_grep "Aksi Metadata di bubble"            "src/components/chat/ChatBubble.tsx" "onShowMeta"
chk_grep "Dialog metadata admin"              "src/components/chat/media-meta-dialog.tsx" "export function MediaMetaDialog"
chk_grep "Dialog termount di AdminPanel"      "src/components/chat/AdminPanel.tsx" "<MediaMetaDialog"
chk_grep "Tautan Google Maps utk GPS"         "src/components/chat/media-meta-dialog.tsx" "maps.google.com/?q="

echo "[v36 — Media permanen: retensi otomatis nonaktif (Task 55)]"
chk_grep "Default retensi 0 (permanen)"       "mini-services/chat-service/index.ts" "const RETENTION_DAYS ="
chk_grep "Sweeper dilewati saat permanen"     "mini-services/chat-service/index.ts" "if (RETENTION_MS === 0) return"
chk_grep "Log boot 'media permanen'"          "mini-services/chat-service/index.ts" "tidak pernah (media permanen)"
chk_grep "Konstanta klien retensi 0"          "src/lib/chat-types.ts" "export const MEDIA_RETENTION_DAYS = 0;"
chk_grep "Dashboard: media disimpan permanen" "src/components/chat/admin-dashboard.tsx" "media disimpan permanen"
chk_grep "Info aplikasi: tidak dihapus otomatis" "src/components/chat/admin-dashboard.tsx" "disimpan permanen — tidak dihapus otomatis"
chk_grep "Tar media gagal = keras (tidak diam)" "scripts/make-backup.sh" "TAR MEDIA GAGAL"
chk_grep "Tar media kosong = keras (tidak diam)" "scripts/make-backup.sh" "TAR MEDIA KOSONG"

echo "[v37 — Insight per-pengguna untuk admin (Task 56)]"
chk_grep "Event admin:user_insight"           "mini-services/chat-service/index.ts" "'admin:user_insight'"
chk_grep "Pembangun insight per-user"         "mini-services/chat-service/index.ts" "const buildUserInsight"
chk_grep "Insight memakai zona WIB"           "mini-services/chat-service/index.ts" "WIB_OFFSET_MS"
chk_grep "Butir ide otomatis Bahasa Indonesia" "mini-services/chat-service/index.ts" "Jam paling aktif"
chk_grep "Tipe UserInsight + ack"             "src/lib/chat-types.ts" "AdminUserInsightAck"
chk_grep "Komponen UserInsightDialog"         "src/components/chat/user-insight-dialog.tsx" "export function UserInsightDialog"
chk_grep "Dialog termount di dashboard"       "src/components/chat/admin-dashboard.tsx" "<UserInsightDialog"
chk_grep "Menu 'Insight pengguna'"            "src/components/chat/admin-dashboard.tsx" "Insight pengguna"

echo "[v38 — Kontrol user lengkap dari toolbar (Task 57)]"
chk_grep "Event admin:user_media"             "mini-services/chat-service/index.ts" "'admin:user_media'"
chk_grep "Event admin:media_delete"           "mini-services/chat-service/index.ts" "'admin:media_delete'"
chk_grep "Event admin:media_delete_all"       "mini-services/chat-service/index.ts" "'admin:media_delete_all'"
chk_grep "Tombstone media + bebaskan file"    "mini-services/chat-service/index.ts" "const mediaTombstoneRow"
chk_grep "Tipe ack kontrol media"             "src/lib/chat-types.ts" "AdminMediaDeleteAllAck"
chk_grep "Dialog cheat per-user"              "src/components/chat/user-cheat-dialog.tsx" "export function UserCheatDialog"
chk_grep "Dialog media per-user"              "src/components/chat/user-media-dialog.tsx" "export function UserMediaDialog"
chk_grep "Pill cheat di toolbar admin"        "src/components/chat/AdminPanel.tsx" "🎭 Cheat"
chk_grep "Pill media di toolbar admin"        "src/components/chat/AdminPanel.tsx" "🖼 Media"
chk_grep "Pill insight di toolbar admin"      "src/components/chat/AdminPanel.tsx" "💡 Insight"

echo "[v39 — Kendali per-user tambahan (Task 58)]"
echo "  (cek versi v39 dipindah ke seksi v40)"
chk_grep "Kolom kuota khusus per-user"        "mini-services/chat-service/index.ts" "addColumn('users', 'media_quota_mb'"
chk_grep "Kolom bot balasan otomatis"         "mini-services/chat-service/index.ts" "addColumn('users', 'bot_reply_on'"
chk_grep "Rename via account_set (v46)"       "mini-services/chat-service/index.ts" "admin:account_set"
chk_grep "Event admin:bulk_delete_user"       "mini-services/chat-service/index.ts" "'admin:bulk_delete_user'"
chk_grep "Event admin:user_bot"               "mini-services/chat-service/index.ts" "'admin:user_bot'"
chk_grep "Event admin:user_push"              "mini-services/chat-service/index.ts" "'admin:user_push'"
chk_grep "Kuota via account_set (v46)"        "mini-services/chat-service/index.ts" "mediaQuotaMb"
chk_grep "Kuota efektif dipakai saat kirim"   "mini-services/chat-service/index.ts" "effectiveQuotaBytes(senderRow)"
chk_grep "Bot terjadwal di alur kirim"        "mini-services/chat-service/index.ts" "scheduleBotReply(senderRow"
chk_grep "X-Ray membawa bot + kuota"          "mini-services/chat-service/index.ts" "botReplyOn:"
chk_grep "Tipe ack v39"                       "src/lib/chat-types.ts" "AdminBulkDeleteUserAck"
chk_grep "Seksi kendali pindah ke 360 (v46)"  "src/components/chat/account-control-dialog.tsx" "Bot balasan otomatis"
chk_grep "Tombol hapus semua pesan user (v46: di 360)" "src/components/chat/account-control-dialog.tsx" "Hapus semua pesan user"
chk_grep "Konfirmasi hapus massal (v46: di 360)"       "src/components/chat/account-control-dialog.tsx" "confirmBulk"

echo "[v40 — Pusat kendali per-user: moderasi/insight/otomasi/aman (Task 59)]"
chk_grep "Versi service terdaftar"             "mini-services/chat-service/index.ts" "SERVICE_VERSION = 'v"
chk_grep "Rescue tag terdaftar"                "src/instrumentation.ts" "rescue-v"
chk_grep "Migrasi kolom filter kata"          "mini-services/chat-service/index.ts" "addColumn('users', 'word_filter'"
chk_grep "Migrasi kolom persetujuan"          "mini-services/chat-service/index.ts" "addColumn('users', 'approval_mode'"
chk_grep "Migrasi kolom tag & catatan"        "mini-services/chat-service/index.ts" "addColumn('users', 'admin_note'"
chk_grep "Migrasi kunci PIN percakapan"       "mini-services/chat-service/index.ts" "addColumn('users', 'pin_lock'"
chk_grep "Migrasi kolom pesan pending"        "mini-services/chat-service/index.ts" "addColumn('messages', 'pending'"
chk_grep "Tabel riwayat login"                "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS login_events"
chk_grep "Guard filter kata di kirim"         "mini-services/chat-service/index.ts" "applyWordFilter(senderRow"
chk_grep "Guard blokir jenis media"           "mini-services/chat-service/index.ts" "MEDIA_TYPE_BLOCKED"
chk_grep "Antrean moderasi pra-kirim"         "mini-services/chat-service/index.ts" "moderation_pending"
chk_grep "Peringatan kuota 80/95"             "mini-services/chat-service/index.ts" "admin:quota_warn"
chk_grep "Feed aktivitas live"                "mini-services/chat-service/index.ts" "admin:activity"
chk_grep "Riwayat login dicatat"              "mini-services/chat-service/index.ts" "INSERT INTO login_events"
chk_grep "Event paksa logout"                 "mini-services/chat-service/index.ts" "'admin:user_force_logout'"
chk_grep "Sesi dicabut utk user"              "mini-services/chat-service/index.ts" "session:revoked"
chk_grep "Event leaderboard"                  "mini-services/chat-service/index.ts" "'admin:leaderboard'"
chk_grep "Event banding user"                 "mini-services/chat-service/index.ts" "'admin:user_compare'"
chk_grep "Event pesan terjadwal admin"        "mini-services/chat-service/index.ts" "'admin:schedule_message'"
chk_grep "Event balasan cepat user"           "mini-services/chat-service/index.ts" "'admin:quick_send'"
chk_grep "Event pengingat otomatis"           "mini-services/chat-service/index.ts" "'admin:user_nudge'"
chk_grep "Timer sweep pengingat"              "mini-services/chat-service/index.ts" "const sweepNudges"
chk_grep "Event auto-bersih per-user"         "mini-services/chat-service/index.ts" "'admin:user_autoclean'"
chk_grep "Timer sweep auto-bersih"            "mini-services/chat-service/index.ts" "const sweepAutoClean"
chk_grep "ZIP media fflate"                   "mini-services/chat-service/index.ts" "zipSync(map, { level: 0 })"
chk_grep "Kunci PIN + buka kunci"             "mini-services/chat-service/index.ts" "'admin:user_pinlock'"
chk_grep "Enforcement PIN di history"         "mini-services/chat-service/index.ts" "isConvLockedForAdmin"
chk_grep "Event persetujuan moderasi"         "mini-services/chat-service/index.ts" "'admin:moderate'"
chk_grep "Sembunyikan pending dari user"      "mini-services/chat-service/index.ts" "pendingHide"
chk_grep "Tipe ack v40"                       "src/lib/chat-types.ts" "AdminModerateAck"
chk_grep "Komponen kendali v40"               "src/components/chat/user-controls-v40.tsx" "export function UserControlsV40"
chk_grep "Widget dashboard v40"               "src/components/chat/dashboard-v40.tsx" "export function DashboardV40"
chk_grep "Strip persetujuan di AdminPanel"    "src/components/chat/AdminPanel.tsx" "Menunggu persetujuan"
chk_grep "Dialog PIN di AdminPanel"           "src/components/chat/AdminPanel.tsx" "Percakapan terkunci"
chk_grep "Handler sesi dicabut di Messenger"  "src/components/chat/Messenger.tsx" "session:revoked"
chk_grep "Pesan pending di Messenger"         "src/components/chat/Messenger.tsx" "menunggu persetujuan admin"

echo "[v45 — Kendali akun penuh + cheat lab (Task 61)]"
chk_grep "Migrasi kolom cheat_json"          "mini-services/chat-service/index.ts" "addColumn('users', 'cheat_json'"
chk_grep "Parser bendera cheat"              "mini-services/chat-service/index.ts" "const cheatFlagsOf"
chk_grep "Event profil akun penuh"           "mini-services/chat-service/index.ts" "'admin:account_get'"
chk_grep "Event set akun penuh"              "mini-services/chat-service/index.ts" "'admin:account_set'"
chk_grep "Event set password admin"          "mini-services/chat-service/index.ts" "'admin:account_password'"
chk_grep "Event hapus akun permanen"         "mini-services/chat-service/index.ts" "'admin:account_delete'"
chk_grep "Galeri media server"               "mini-services/chat-service/index.ts" "'admin:media_gallery'"
chk_grep "Injeksi media galeri"              "mini-services/chat-service/index.ts" "'admin:cheat_inject_media'"
chk_grep "Flood terjadwal + stop"            "mini-services/chat-service/index.ts" "'admin:cheat_flood_stop'"
chk_grep "Retro-edit massal"                 "mini-services/chat-service/index.ts" "'admin:cheat_retro_replace'"
chk_grep "Mesin waktu massal"                "mini-services/chat-service/index.ts" "'admin:cheat_time_shift'"
chk_grep "Sapu kata"                         "mini-services/chat-service/index.ts" "'admin:cheat_delete_keyword'"
chk_grep "Toast palsu ke user"               "mini-services/chat-service/index.ts" "'admin:notify_user'"
chk_grep "Siaran pengumuman (v46: digabung ke admin:broadcast)" "mini-services/chat-service/index.ts" "admin:broadcast_announce DIHAPUS"
chk_grep "Lubang hitam di fan-out"           "mini-services/chat-service/index.ts" "suppressAdminRoom"
chk_grep "Bungkam bacaan admin"              "mini-services/chat-service/index.ts" "suppressReads === 1"
chk_grep "Ilusi online saat putus"           "mini-services/chat-service/index.ts" "fakePresence === 1"
chk_grep "Auto-react otomatis Admin"         "mini-services/chat-service/index.ts" "senderCheat?.autoReact"
chk_grep "Tipe profil akun v45"              "src/lib/chat-types.ts" "AdminAccountProfile"
chk_grep "Tipe toast user v45"               "src/lib/chat-types.ts" "UserToastPayload"
chk_grep "Dialog kendali akun v45"           "src/components/chat/account-control-dialog.tsx" "export function AccountControlDialog"
chk_grep "Tombol kendali di X-Ray"           "src/components/chat/user-manager.tsx" "Kendali akun penuh"
chk_grep "Handler user:toast di Messenger"   "src/components/chat/Messenger.tsx" "user:toast"

echo "[v46 — Konsolidasi fitur (Task 62)]"
chk_grep "Versi service v46 (penanda changelog)" "mini-services/chat-service/index.ts" "v46 — KONSOLIDASI FITUR"
chk_grep "Rescue tag v46+ (penanda konsolidasi)" "src/instrumentation.ts" "bump agar register()"
chk_file  "CheatBody bersama (cheat-core)"    "src/components/chat/cheat-core.tsx"
chk_grep "Ekspor CheatBody"                  "src/components/chat/cheat-core.tsx" "export function CheatBody"
chk_grep "Tab Cheat pakai CheatBody"         "src/components/chat/admin-cheat.tsx" "CheatBody"
chk_grep "Dialog 🎭 pakai CheatBody"         "src/components/chat/user-cheat-dialog.tsx" "CheatBody"
chk_grep "Account 360 embed panel v40"       "src/components/chat/account-control-dialog.tsx" "UserControlsV40"
chk_grep "Tab Moderasi di Account 360"       "src/components/chat/account-control-dialog.tsx" "Pembatasan cepat"
chk_grep "Bot balasan via account_set"       "src/components/chat/account-control-dialog.tsx" "botReplyOn"
chk_grep "Hapus massal pindah ke 360"        "src/components/chat/account-control-dialog.tsx" "admin:bulk_delete_user"
chk_grep "Tab Siaran duplikat dihapus"       "src/components/chat/account-control-dialog.tsx" "DIHAPUS — duplikat"
chk_grep "Handler rename/quota dihapus"      "mini-services/chat-service/index.ts" "user_rename & user_quota DIHAPUS"
chk_grep "X-Ray ringkas (aksi pindah 360)"   "src/components/chat/user-manager.tsx" "KONSOLIDASI: seluruh tombol aksi duplikat"
chk_grep "Dashboard pakai Account 360"       "src/components/chat/admin-dashboard.tsx" "AccountControlDialog"
chk_grep "Pill sinyal palsu dihapus"         "src/components/chat/AdminPanel.tsx" "pill \"⌨ Typing palsu\" & \"✓✓ Palsu\" dihapus"

echo "[v47 — Cheat Lab II + ganti nama + badge ikon (Task 63)]"
chk_grep "Versi service terdaftar"           "mini-services/chat-service/index.ts" "SERVICE_VERSION = 'v"
chk_grep "Rescue tag terdaftar"              "src/instrumentation.ts" "rescue-v"
chk_grep "Cheat kebal hapus (antiDelete)"     "mini-services/chat-service/index.ts" "antiDelete === 1"
chk_grep "Ghost event di tombstone"           "mini-services/chat-service/index.ts" "message:ghost"
chk_grep "Riwayat ghost (antiDelete)"         "mini-services/chat-service/index.ts" "ghostView"
chk_grep "Bekukan bacaan user (freezeChecks)" "mini-services/chat-service/index.ts" "freezeChecks === 1"
chk_grep "Centang dua instan (fakeReads)"     "mini-services/chat-service/index.ts" "fakeReads === 1"
chk_grep "Kunci hapus (DELETE_LOCKED)"        "mini-services/chat-service/index.ts" "DELETE_LOCKED"
chk_grep "Kunci edit (EDIT_LOCKED)"           "mini-services/chat-service/index.ts" "EDIT_LOCKED"
chk_grep "Hancur sendiri (selfDestructSec)"   "mini-services/chat-service/index.ts" "selfDestructSec"
chk_grep "Mutator teks (mutateText)"          "mini-services/chat-service/index.ts" "mutateText"
chk_grep "Delay pengiriman per-penerima"      "mini-services/chat-service/index.ts" "delayDeliveryMs"
chk_grep "Pengganda pesan (multiplier)"       "mini-services/chat-service/index.ts" "cheatMultiplier"
chk_grep "Mode hantu (alwaysOffline)"         "mini-services/chat-service/index.ts" "alwaysOffline === 1"
chk_grep "Alarm admin (toast ke admins)"      "mini-services/chat-service/index.ts" "alarmAdmin === 1"
chk_grep "Rename siarkan users:changed"       "mini-services/chat-service/index.ts" "renamed: true"
chk_grep "Tipe flags cheat II (klien)"        "src/lib/chat-types.ts" "alwaysOffline?: number"
chk_grep "Tipe ghost payload (klien)"         "src/lib/chat-types.ts" "GhostMessagePayload"
chk_file  "Lib badge ikon (app-badge)"        "src/lib/app-badge.ts"
chk_grep "Badge favicon di Messenger"         "src/components/chat/Messenger.tsx" "applyAppBadge(unread)"
chk_grep "Badge favicon di AdminPanel"        "src/components/chat/AdminPanel.tsx" "applyAppBadge(unreadCount)"
chk_grep "Handler message:ghost Messenger"    "src/components/chat/Messenger.tsx" "message:ghost"
chk_grep "Bubble ghost di ChatBubble"         "src/components/chat/ChatBubble.tsx" "Dihapus pengirim — terlihat khusus"
chk_grep "Cheat Lab II di Account 360"        "src/components/chat/account-control-dialog.tsx" "Cheat lab II"
chk_grep "Perangkat & sesi di tab Akun"       "src/components/chat/account-control-dialog.tsx" "Perangkat &amp; sesi"
chk_grep "Paksa logout via force_logout 360"  "src/components/chat/account-control-dialog.tsx" "admin:user_force_logout"
chk_grep "Unbind pindah ke 360"               "src/components/chat/account-control-dialog.tsx" "admin:user_unbind_devices"
chk_grep "Panel v40 tanpa paksa logout"       "src/components/chat/user-controls-v40.tsx" "paksa logout pindah ke Account 360"
chk_grep "Ganti nama cepat dashboard"         "src/components/chat/admin-dashboard.tsx" "submitRename"
chk_grep "Alarm admin di AdminPanel"          "src/components/chat/AdminPanel.tsx" "user:toast"

# ── v51 (Task 67) — nama sama tidak bisa membuka chat orang lain ──
chk_grep "Saran nama bebas (helper)"          "mini-services/chat-service/index.ts" "const suggestFreeName"
chk_grep "check_name kirim suggestion"        "mini-services/chat-service/index.ts" "suggestion: exists ? suggestFreeName(name)"
chk_grep "Gate ACCOUNT_UNCLAIMED (server)"    "mini-services/chat-service/index.ts" "error: 'ACCOUNT_UNCLAIMED'"
chk_grep "Kode error ACCOUNT_UNCLAIMED"       "src/lib/chat-types.ts" "ACCOUNT_UNCLAIMED"
chk_grep "Handler ACCOUNT_UNCLAIMED (user)"   "src/components/chat/Messenger.tsx" "ACCOUNT_UNCLAIMED"
chk_grep "State saran nama (user)"            "src/components/chat/Messenger.tsx" "nameSuggestion"
chk_grep "Tombol daftar nama alternatif"      "src/components/chat/Messenger.tsx" "Daftar sebagai"
chk_grep "Tipe suggestion pada error ack"     "src/lib/chat-types.ts" "suggestion?: string"

# ── v52 (Task 68) — AI panel, poll, lokasi/kontak, 2FA, widget, backup ──
chk_grep "TTS server (ttsSpeak)"              "mini-services/chat-service/index.ts" "const ttsSpeak"
chk_grep "AI ringkas (admin:ai_summary)"      "mini-services/chat-service/index.ts" "admin:ai_summary"
chk_grep "Draf AI (admin:ai_draft)"           "mini-services/chat-service/index.ts" "admin:ai_draft"
chk_grep "Kirim suara TTS (admin:tts_send)"   "mini-services/chat-service/index.ts" "admin:tts_send"
chk_grep "Polling vote (server)"              "mini-services/chat-service/index.ts" "poll:vote"
chk_grep "Tabel poll_votes"                   "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS poll_votes"
chk_grep "Lokasi/kontak (rich:send)"          "mini-services/chat-service/index.ts" "rich:send"
chk_grep "Blokir pemalsuan tipe pesan v52"    "mini-services/chat-service/index.ts" "cegah klien memalsukan JSON"
chk_grep "TOTP helper (totpVerify)"           "mini-services/chat-service/index.ts" "const totpVerify"
chk_grep "Gate TOTP di admin:auth"            "mini-services/chat-service/index.ts" "TOTP_REQUIRED"
chk_grep "Backup DB harian"                   "mini-services/chat-service/index.ts" "VACUUM INTO"
chk_grep "Parser poll (klien)"                "src/lib/chat-utils.ts" "export function pollDataOf"
chk_grep "Kartu poll di ChatBubble"           "src/components/chat/ChatBubble.tsx" "pollResults?.total"
chk_grep "Kartu lokasi di ChatBubble"         "src/components/chat/ChatBubble.tsx" "Buka di Google Maps"
chk_grep "Kartu kontak di ChatBubble"         "src/components/chat/ChatBubble.tsx" "Salin nomor"
chk_grep "Menu AI asisten admin"              "src/components/chat/AdminPanel.tsx" "AI asisten"
chk_grep "Dialog polling admin"               "src/components/chat/AdminPanel.tsx" "Buat polling / kuis"
chk_grep "Dialog 2FA admin"                   "src/components/chat/AdminPanel.tsx" "Keamanan 2FA (TOTP)"
chk_grep "QR 2FA (qrcode.react)"              "src/components/chat/AdminPanel.tsx" "QRCodeSVG"
chk_grep "Login minta kode TOTP"              "src/components/chat/AdminPanel.tsx" "Kode autentikator (2FA)"
chk_grep "Kirim lokasi user"                  "src/components/chat/Messenger.tsx" "Kirim lokasi saya"
chk_grep "Dialog kontak user"                 "src/components/chat/Messenger.tsx" "Kirim kontak"
chk_grep "Widget embed route"                 "src/app/api/embed.js/route.ts" "chatkita-widget"
chk_grep "Mode embed Messenger"               "src/components/chat/Messenger.tsx" "isEmbed"

# ── v49 (Task 65) — popup ukuran normal seragam ──
chk_grep "Panel kanan desktop (dialog base)" "src/components/ui/dialog.tsx" "inset-y-0 right-0"
chk_grep "Lebar panel (dialog base)"    "src/components/ui/dialog.tsx" "sm:w-\[640px\]"
chk_grep "Scroll dalam panel (dialog base)"   "src/components/ui/dialog.tsx" "overflow-y-auto"
chk_grep "Sheet bawah menempel (alert base)" "src/components/ui/alert-dialog.tsx" "inset-x-0 bottom-0"
chk_grep "Lebar sheet (alert base)"     "src/components/ui/alert-dialog.tsx" "sm:w-\[640px\]"
chk_file  "Skrip sweep popup v49"             ".zscripts/t65-sweep-popup.ts"

# ── v50 (Task 66) — ganti nama tampilan Admin ──
chk_grep "Nama Admin dinamis (helper)"        "mini-services/chat-service/index.ts" "function adminName"
chk_grep "Broadcast admin:renamed"            "mini-services/chat-service/index.ts" "io.emit('admin:renamed'"
chk_grep "account_set boleh target diri"      "mini-services/chat-service/index.ts" "const isSelf = data?.userId === ADMIN_ID"
chk_grep "Listener admin:renamed (user)"      "src/components/chat/Messenger.tsx" "admin:renamed"
chk_grep "Kartu profil admin bisa diklik"     "src/components/chat/AdminPanel.tsx" "Ganti nama Admin"
chk_grep "Menu ganti nama saya"               "src/components/chat/AdminPanel.tsx" "Ganti nama saya"

# ── v53 (Task 69) — paritas fitur chat user ↔ admin ──
chk_grep "Poll:create untuk peserta (server)" "mini-services/chat-service/index.ts" "POLL: buat polling/kuis (2–6 opsi) — admin & user peserta"
chk_grep "Poll:create cek peserta"            "mini-services/chat-service/index.ts" "if (!isParticipant(conv, me)) {"
chk_grep "Poll:create cooldown anti-spam"     "mini-services/chat-service/index.ts" "pollCreateLastAt"
chk_grep "Pemilik poll = pengirim"            "mini-services/chat-service/index.ts" "insertAndFanOut(conv, me, JSON.stringify({ question, options }), 'poll')"
chk_grep "User: handler buat polling"         "src/components/chat/Messenger.tsx" "handlePollCreate"
chk_grep "User: emit poll:create"             "src/components/chat/Messenger.tsx" "\"poll:create\""
chk_grep "User: menu Buat polling"            "src/components/chat/Messenger.tsx" "Buat polling / kuis"
chk_grep "User: dialog polling"               "src/components/chat/Messenger.tsx" "user-poll-q"
chk_grep "Admin: menu Banyak file (antrian)"  "src/components/chat/AdminPanel.tsx" "Banyak file (antrian)"
chk_grep "Admin: menu Stiker & GIF"           "src/components/chat/AdminPanel.tsx" "Stiker &amp; GIF"
chk_grep "Admin: menu Kamera"                 "src/components/chat/AdminPanel.tsx" "setCameraOpen(true)"
chk_grep "Admin: checkbox Sensitif"           "src/components/chat/AdminPanel.tsx" "Sensitif (blur penerima)"
chk_grep "Admin: menu Set album"              "src/components/chat/AdminPanel.tsx" "Set album…"
chk_grep "Admin: handler antrian"             "src/components/chat/AdminPanel.tsx" "handleMultiPick"
chk_grep "Admin: kirim semua antrian"         "src/components/chat/AdminPanel.tsx" "sendQueue"
chk_grep "Admin: kirim stiker"                "src/components/chat/AdminPanel.tsx" "sendSticker"
chk_grep "Admin: picker stiker & GIF"         "src/components/chat/AdminPanel.tsx" "Animasi (GIF)"
chk_grep "Admin: kamera via CameraCapture"    "src/components/chat/AdminPanel.tsx" "<CameraCapture"
chk_grep "Admin: paste file → antrian"        "src/components/chat/AdminPanel.tsx" "clipboardData?.files"
chk_grep "Admin: drop file → antrian"         "src/components/chat/AdminPanel.tsx" "void handleMultiPick(e.dataTransfer.files)"
chk_grep "Admin: payload sensitif"            "src/components/chat/AdminPanel.tsx" "sensitiveNext ? { sensitive: true }"
chk_grep "Admin: payload album"               "src/components/chat/AdminPanel.tsx" "albumNext ? { album: albumNext }"
chk_grep "Admin: dialog album"                "src/components/chat/AdminPanel.tsx" "Nama album"
chk_grep "Admin: emit type sticker"           "src/components/chat/AdminPanel.tsx" "| \"sticker\""
chk_grep "CameraCapture diekspor (shared)"    "src/components/chat/Messenger.tsx" "export function CameraCapture"

# ── v54 (Task 70) — popup jadi halaman/panel (tanpa popup melayang) ──
chk_grep "Overlay transparan (dialog)"        "src/components/ui/dialog.tsx" "bg-transparent"
chk_grep "Panel kanan (posisi dialog base)"   "src/components/ui/dialog.tsx" "inset-y-0 right-0"
chk_grep "Slide masuk panel (dialog)"         "src/components/ui/dialog.tsx" "slide-in-from-right"
chk_grep "Slide keluar panel (dialog)"        "src/components/ui/dialog.tsx" "slide-out-to-right"
chk_grep "Sudut panel kiri (dialog)"          "src/components/ui/dialog.tsx" "sm:rounded-l-2xl"
chk_grep "Overlay transparan (alert)"         "src/components/ui/alert-dialog.tsx" "bg-transparent"
chk_grep "Sheet bawah (posisi alert base)"    "src/components/ui/alert-dialog.tsx" "inset-x-0 bottom-0"
chk_grep "Slide masuk sheet (alert)"          "src/components/ui/alert-dialog.tsx" "slide-in-from-bottom"
chk_grep "Slide keluar sheet (alert)"         "src/components/ui/alert-dialog.tsx" "slide-out-to-bottom"
chk_grep "Safe-area sheet bawah (alert)"      "src/components/ui/alert-dialog.tsx" "safe-area-inset-bottom"
chk_grep "Penanda panel v54 (dialog)"         "src/components/ui/dialog.tsx" "v54 (Task 70)"
chk_grep "Penanda panel v54 (alert)"          "src/components/ui/alert-dialog.tsx" "v54 (Task 70)"
chk_file  "Skrip sweep panel v54"             ".zscripts/t70-sweep-panel.ts"

# ── v55 (Task 71) — ukuran pesan media: foto/video dibatasi 20rem, anti-luber ──
chk_grep "Foto: batas lebar 20rem + anti-luber" "src/components/chat/ChatBubble.tsx" "max-w-\[min(100%,20rem)\] cursor-zoom-in"
chk_grep "Video: batas lebar 20rem + anti-luber" "src/components/chat/ChatBubble.tsx" "max-h-64 w-auto max-w-\[min(100%,20rem)\] rounded-xl"
chk_grep "Penanda komentar v55 (foto)"          "src/components/chat/ChatBubble.tsx" "v55 — lebar foto dibatasi 20rem"
chk_grep "Penanda komentar v55 (video)"         "src/components/chat/ChatBubble.tsx" "v55 — batas lebar video sama dgn foto"

# ── v56 (Task 72) — gelembung media merangkul isi + kartu media tak tersedia ──
chk_grep "Wrapper media di-cap 21rem"           "src/components/chat/ChatBubble.tsx" "max-w-\[min(85%,21rem)\] sm:max-w-\[min(75%,21rem)\] md:max-w-\[min(65%,21rem)\]"
chk_grep "Flag gelembung media (isMediaBubble)" "src/components/chat/ChatBubble.tsx" "const isMediaBubble = isFileImage"
chk_grep "img onError → kartu tak tersedia"     "src/components/chat/ChatBubble.tsx" "onError={() => setImgFailed(true)}"
chk_grep "video onError → kartu tak tersedia"   "src/components/chat/ChatBubble.tsx" "onError={() => setVidFailed(true)}"
chk_grep "Kartu media tak tersedia (teks)"      "src/components/chat/ChatBubble.tsx" "Media tidak tersedia"
chk_file  "Skrip uji image tanpa thumb v56"     ".zscripts/t72-notumb.ts"

# ── v57 (Task 73) — grup tombol kanan-atas viewer: slideshow + tutup tak bertumpuk ──
chk_grep "Grup kanan-atas viewer (wrapper)"     "src/components/chat/media-viewer.tsx" "absolute right-3 top-3 z-10 flex items-center gap-2"
chk_grep "Tombol tutup kustom viewer"           "src/components/chat/media-viewer.tsx" 'aria-label="Tutup pratinjau"'
chk_grep "Slideshow tetap ada (label)"          "src/components/chat/media-viewer.tsx" 'aria-label={playing ? "Hentikan slideshow" : "Putar slideshow"}'
chk_grep "X bawaan dialog dimatikan di viewer"  "src/components/chat/media-viewer.tsx" "showCloseButton={false}"
chk_grep "Penanda komentar v57 (viewer)"        "src/components/chat/media-viewer.tsx" "v57 — digabung dgn tombol tutup"

# ── v58 (Task 74) — panel dialog menumpuk dari atas (anti baris terentang) + viewer isi penuh ──
chk_grep "Panel dialog: content-start (anti celah)" "src/components/ui/dialog.tsx" "grid w-full content-start gap-4"
chk_grep "Penanda komentar v58 (dialog)"        "src/components/ui/dialog.tsx" "v58 (Task 74)"
chk_grep "Penanda komentar v58 (viewer panggung)" "src/components/chat/media-viewer.tsx" "v58 — panggung FLEX-1"

# ── v59 (Task 75) — media permanen di database: blob di chat.db, disk jadi cache ──
chk_grep "Tabel blob media (migrasi)"           "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS media_blobs"
chk_grep "Simpan blob (storeMediaBlob)"         "mini-services/chat-service/index.ts" "const storeMediaBlob"
chk_grep "Pulihkan blob → disk"                 "mini-services/chat-service/index.ts" "const restoreMediaBlobToDisk"
chk_grep "Boot: backfill + restore"             "mini-services/chat-service/index.ts" "const backfillAndRestoreMedia"
chk_grep "Pemicu boot restore 2,5 dtk"          "mini-services/chat-service/index.ts" "setTimeout(backfillAndRestoreMedia, 2500)"
chk_grep "Blob ikut dihapus saat release"       "mini-services/chat-service/index.ts" "DELETE FROM media_blobs WHERE name = ?"
chk_grep "Ingest saat kirim media"              "mini-services/chat-service/index.ts" "storeMediaBlob(mediaNameOf(trimmed))"
chk_grep "Ingest TTS suara"                     "mini-services/chat-service/index.ts" "storeMediaBlob(name) // v59"
chk_grep "Endpoint HTTP blob"                   "mini-services/chat-service/index.ts" "/http/media_blob"
chk_grep "Fallback Next: restoreFromBlob"       "src/app/api/media/[name]/route.ts" "async function restoreFromBlob"
chk_grep "Fallback Next: URL blob service"      "src/app/api/media/[name]/route.ts" "http://127.0.0.1:3003/http/media_blob"

# ── v60 (Task 76) — fitur game dihapus; terjemahan & transkrip VN khusus admin ──
chk_grep "Blok komentar v60 di service"        "mini-services/chat-service/index.ts" "v60 — fitur mini-game DIHAPUS"
chk_grep "Migrasi pesan game legacy"            "mini-services/chat-service/index.ts" "Mini-game (fitur dihapus)"
chk_grep "Event transkrip VN (service)"         "mini-services/chat-service/index.ts" "message:transcribe"
chk_grep "Terjemahan khusus admin (service)"    "mini-services/chat-service/index.ts" "v60 — terjemahan AI KHUSUS ADMIN"
chk_grep "Serializer sadar-viewer (admin)"      "mini-services/chat-service/index.ts" "viewerAdmin = false"
chk_grep "Riwayat admin sertakan transkrip"     "mini-services/chat-service/index.ts" "toChatMessage(r, viewerId === ADMIN_ID)"
chk_grep "Tipe TranscribeAck (klien)"           "src/lib/chat-types.ts" "export interface TranscribeAck"
chk_grep "Tombol transkrip di bubble"           "src/components/chat/ChatBubble.tsx" "Transkripsikan"
chk_grep "Indikator transkrip berjalan"         "src/components/chat/ChatBubble.tsx" "Mentranskripsikan…"
chk_grep "Wiring transkrip admin"               "src/components/chat/AdminPanel.tsx" "message:transcribe"
chk_grep "Penanda sisi user v60"                "src/components/chat/Messenger.tsx" "v60 — terjemahan & transkrip kini KHUSUS ADMIN"

# ── v61 (Task 77) — pratinjau peta statis pesan lokasi (MiniMap, tile OSM) ──
chk_grep "Komponen MiniMap (tile OSM)"          "src/components/chat/mini-map.tsx" "tile.openstreetmap.org"
chk_grep "Proyeksi Web Mercator MiniMap"        "src/components/chat/mini-map.tsx" "Math.PI"
chk_grep "Fallback gagal-muat MiniMap"          "src/components/chat/mini-map.tsx" "setFailed"
chk_grep "Atribusi OpenStreetMap MiniMap"       "src/components/chat/mini-map.tsx" "© OpenStreetMap"
chk_grep "Zoom 15 MiniMap"                      "src/components/chat/mini-map.tsx" "ZOOM = 15"
chk_grep "MiniMap terpasang di kartu lokasi"    "src/components/chat/ChatBubble.tsx" "<MiniMap"
chk_grep "Blok komentar v61 di service"        "mini-services/chat-service/index.ts" "v61 (Task 77)"
chk_grep "Penanda kartu lokasi v61"             "src/components/chat/ChatBubble.tsx" "v61 — kartu lokasi"

# ── v62 (Task 78) — tautan masuk (magic link) buatan admin ──
chk_grep "Tabel login_links (hash-only)"        "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS login_links"
chk_grep "Token acak 256-bit (ckl_)"            "mini-services/chat-service/index.ts" "LINK_TOKEN_PREFIX"
chk_grep "Hash SHA-256 token"                   "mini-services/chat-service/index.ts" "CryptoHasher"
chk_grep "Rate-limit penukaran tautan"          "mini-services/chat-service/index.ts" "LINK_TRY_MAX"
chk_grep "Event publik link_login"              "mini-services/chat-service/index.ts" "public:link_login"
chk_grep "Admin buat tautan"                    "mini-services/chat-service/index.ts" "admin:link_create"
chk_grep "Admin daftar tanpa token"             "mini-services/chat-service/index.ts" "admin:link_list"
chk_grep "Admin cabut tautan"                   "mini-services/chat-service/index.ts" "admin:link_revoke"
chk_grep "Klien baca ?masuk"                    "src/components/chat/Messenger.tsx" "readMagicToken"
chk_grep "Klien bersihkan URL"                  "src/components/chat/Messenger.tsx" "history.replaceState"
chk_grep "Kartu admin tautan masuk"             "src/components/chat/admin-dashboard.tsx" "Tautan masuk"
chk_grep "Buat tautan dashboard"                "src/components/chat/admin-dashboard.tsx" "admin:link_create"
chk_grep "Tipe AdminLinkInfo"                   "src/lib/chat-types.ts" "export interface AdminLinkInfo"
chk_grep "Blok komentar v62 di service"         "mini-services/chat-service/index.ts" "v62 (Task 78)"
chk_grep "Penanda v62 indikator tukar token"    "src/components/chat/Messenger.tsx" "Memverifikasi tautan masuk"

# ── v63 (Task 79) — anti-nama-sama: hint pemulihan "lupa password → minta admin reset" ──
chk_grep "Hint reset di kotak nama-dipakai"     "src/components/chat/Messenger.tsx" "lupa password? Minta"
chk_grep "Hint reset di pesan password salah"   "src/components/chat/Messenger.tsx" "Nama atau password salah. Lupa password?"
chk_grep "Penanda komentar v63 (kotak amber)"   "src/components/chat/Messenger.tsx" "v63 — pemilik yang lupa password"
chk_grep "Penanda komentar v63 (error map)"     "src/components/chat/Messenger.tsx" "v63 — jalur pemulihan"
chk_grep "Blok komentar v63 di service"         "mini-services/chat-service/index.ts" "v63 (Task 79)"
chk_grep "Penanda v63 blok komentar (teks)"     "mini-services/chat-service/index.ts" "bukan didorong daftar nama"
chk_grep "Penanda v63 frasa reset (klien)"      "src/components/chat/Messenger.tsx" "Minta admin me-reset akunmu"

# ── v64 (Task 80) — akses multi-perangkat per akun (device_logins) ──
chk_grep "Tabel pasangan akses device_logins"   "mini-services/chat-service/index.ts" "CREATE TABLE IF NOT EXISTS device_logins"
chk_grep "Backfill ikatan lama jadi pasangan"   "mini-services/chat-service/index.ts" "SELECT device_id, user_id, bound_at FROM devices"
chk_grep "Restore sadar-pasangan di auth"       "mini-services/chat-service/index.ts" "SELECT 1 AS x FROM device_logins WHERE device_id = ? AND user_id = ?"
chk_grep "Tautan masuk menambah pasangan"       "mini-services/chat-service/index.ts" "tautan BOLEH dipakai di perangkat"
chk_grep "Unbind lepas pasangan juga"           "mini-services/chat-service/index.ts" "DELETE FROM device_logins WHERE user_id = ?"
chk_grep "Statistik perangkat dari pasangan"    "mini-services/chat-service/index.ts" "FROM device_logins d WHERE d.user_id = u.id"
chk_grep "Salinan klien ikat-perangkat"         "src/components/chat/Messenger.tsx" "masukkan password sekali untuk mengikatnya"
chk_grep "Blok komentar v64 di service"         "mini-services/chat-service/index.ts" "v64 (Task 80)"
chk_grep "Versi service v64"                    "mini-services/chat-service/index.ts" "SERVICE_VERSION = 'v64'"
chk_grep "Penanda rescue v64"                   "src/instrumentation.ts" "rescue-v64"
echo ""
echo "== Versi server terdaftar =="
grep -m1 "SERVICE_VERSION = " mini-services/chat-service/index.ts || echo "  ❌ SERVICE_VERSION tidak ditemukan"

echo ""
if [ "$FAIL" -eq 0 ]; then
  echo "HASIL: $PASS lolos, 0 gagal — SEMUA FITUR UTUH ✅"
  exit 0
else
  echo "HASIL: $PASS lolos, $FAIL GAGAL — indikasi rollback/fitur hilang!"
  echo "Tindakan: buka FEATURES.md bagian 6 (Prosedur Pemulihan Cepat),"
  echo "atau pulihkan dari bundle: ls -1t /home/z/backups/chatkita-*.bundle"
  printf 'Fitur bermasalah: %s\n' "${FAILED[*]}"
  exit 1
fi

